load("//tools/build_defs/go:go_library.bzl", "go_library")
load("//tools/build_defs/go:go_test.bzl", "go_test")

go_library(
    name = "cloudsqlpgcreateinstances",
    srcs = ["cloudsqlpgcreateinstances.go"],
)

go_test(
    name = "cloudsqlpgprecheckmajorversionupgrade_test",
    srcs = ["cloudsqlpgcreateinstances_test.go"],
)
