# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: "detect-changes"
    name: "gcr.io/cloud-builders/git"
    waitFor: ["-"] 
    entrypoint: "bash"
    args:
      - -c
      - |
        git fetch --unshallow || true
        git fetch origin main > /dev/null 2>&1
        git diff --name-only origin/main...HEAD > /workspace/changed_files.txt

  - id: "install-dependencies"
    name: golang:1
    waitFor: ["-"]
    env:
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
    script: |
      go get -d ./...

  - id: "compile-test-binary"
    name: golang:1
    waitFor: ["install-dependencies"]
    env:
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
    script: |
      go test -c -race -cover \
      -coverpkg=./internal/sources/...,./internal/tools/... \
      $(go list ./tests/... | grep -v '/tests/prompts')
      chmod +x .ci/test_with_coverage.sh

  - id: "http"
    name: golang:1
    waitFor: ["compile-test-binary", "detect-changes"]
    entrypoint: /bin/bash
    env:
      - "GOPATH=/gopath"
    secretEnv: ["CLIENT_ID"]
    volumes:
      - name: "go"
        path: "/gopath"
    args:
      - -c
      - |
        PATTERN="http|internal/server/|.ci/"

        if grep -qE "$$PATTERN" /workspace/changed_files.txt; then
          echo "Changes detected. Running HTTP tests..."
          .ci/test_with_coverage.sh \
            "HTTP" \
            http \
            http
        else
          echo "No relevant changes for HTTP. Skipping shard."
          exit 0
        fi

availableSecrets:
  secretManager:
    # Common secrets
    - versionName: projects/$PROJECT_ID/secrets/client_id/versions/latest
      env: CLIENT_ID


options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
  substitutionOption: "ALLOW_LOOSE"
  dynamicSubstitutions: true
  pool:
    name: projects/$PROJECT_ID/locations/us-central1/workerPools/integration-testing # Necessary for VPC network connection

substitutions:
  _DATABASE_NAME: test_database
  _FIREBIRD_DATABASE_NAME: /firebird/test_database.fdb
  _REGION: "us-central1"
  _CLOUD_SQL_POSTGRES_INSTANCE: "cloud-sql-pg-testing"
  _ALLOYDB_POSTGRES_CLUSTER: "alloydb-pg-testing"
  _ALLOYDB_POSTGRES_INSTANCE: "alloydb-pg-testing-instance"
  _ALLOYDB_AI_NL_CLUSTER: "alloydb-ai-nl-testing"
  _ALLOYDB_AI_NL_INSTANCE: "alloydb-ai-nl-testing-instance"
  _BIGTABLE_INSTANCE: "bigtable-testing-instance"
  _HEALTHCARE_DATASET: "test-dataset"
  _POSTGRES_HOST: 127.0.0.1
  _POSTGRES_PORT: "5432"
  _SPANNER_INSTANCE: "spanner-testing"
  _NEO4J_DATABASE: "neo4j"
  _CLOUD_SQL_MSSQL_INSTANCE: "cloud-sql-mssql-testing"
  _CLOUD_SQL_MYSQL_INSTANCE: "cloud-sql-mysql-testing"
  _MYSQL_HOST: 127.0.0.1
  _MYSQL_PORT: "3306"
  _MSSQL_HOST: 127.0.0.1
  _MSSQL_PORT: "1433"
  _DGRAPHURL: "https://play.dgraph.io"
  _COUCHBASE_BUCKET: "couchbase-bucket"
  _COUCHBASE_SCOPE: "couchbase-scope"
  _LOOKER_LOCATION: "us"
  _LOOKER_PROJECT: "149671255749"
  _LOOKER_VERIFY_SSL: "true"
  _TIDB_HOST: 127.0.0.1
  _TIDB_PORT: "4000"
  _CLICKHOUSE_DATABASE: "default"
  _CLICKHOUSE_PORT: "8123"
  _CLICKHOUSE_PROTOCOL: "http"
  _FIREBIRD_HOST: 127.0.0.1
  _FIREBIRD_PORT: "3050"
  _TRINO_HOST: 127.0.0.1
  _TRINO_PORT: "8080"
  _TRINO_CATALOG: "memory"
  _TRINO_SCHEMA: "default"
  _OCEANBASE_PORT: "2883"
  _OCEANBASE_DATABASE: "oceanbase"
  _MINDSDB_PORT: "47335"
  _MINDSDB_DATABASE: "mindsdb_test"
  _YUGABYTEDB_DATABASE: "yugabyte"
  _YUGABYTEDB_PORT: "5433"
  _YUGABYTEDB_LOADBALANCE: "false"
  _ORACLE_SERVER_NAME: "FREEPDB1"
  _SINGLESTORE_HOST: 127.0.0.1
  _SINGLESTORE_PORT: "3308"
  _SINGLESTORE_DATABASE: "singlestore"
  _SINGLESTORE_USER: "root"
  _COCKROACHDB_HOST: 127.0.0.1
  _COCKROACHDB_PORT: "26257"
  _COCKROACHDB_USER: "root"
  _MARIADB_PORT: "3307"
  _MARIADB_DATABASE: test_database
  _SNOWFLAKE_DATABASE: "test"
  _SNOWFLAKE_SCHEMA: "PUBLIC"
