load("//tools/build_defs/go:go_library.bzl", "go_library")
load("//tools/build_defs/go:go_test.bzl", "go_test")

go_library(
    name = "cloudsqlpgupgradeprecheck",
    srcs = ["cloudsqlpgupgradeprecheck.go"],
)

go_test(
    name = "cloudsqlpgupgradeprecheck_test",
    srcs = ["cloudsqlpgupgradeprecheck_test.go"],
)
