apiVersion: v2
name: mcp-toolbox
description: A Helm chart for MCP Toolbox for Databases, an open source MCP server for databases.

# MCP Toolbox for Databases is an open source MCP server for databases. 
# It enables you to develop tools easier, faster, and more securely by handling the complexities
# such as connection pooling, authentication, and more.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.7.0"
