load("//tools/build_defs/go:go_library.bzl", "go_library")
load("//tools/build_defs/go:go_test.bzl", "go_test")

go_library(
    name = "cloudsqlpgprecheckmajorversionupgrade",
    srcs = ["cloudsqlpgprecheckmajorversionupgrade.go"],
)

go_test(
    name = "cloudsqlpgprecheckmajorversionupgrade_test",
    srcs = ["cloudsqlpgprecheckmajorversionupgrade_test.go"],
)
